### ISSUE TITLE
ipk

### ISSUE THREAD

**Issue by syk6666** [adyanth/openwrt-tailscale-enabler#17]
请问这个可以生成ipk文件安装吗？ 更新下载二进制文件 怎样解压缩 是直接解压缩上传换文件 还是需要命令解压 请具体的说一下 谢谢 谢谢

**Comment by adyanth** [comment]
There is no ipk file since this is not a package. To use it, please follow the instructions on the [README](https://github.com/adyanth/openwrt-tailscale-enabler/blob/main/README.md). Download the [.tgz package from releases](https://github.com/adyanth/openwrt-tailscale-enabler/releases) to openWRT. Then proceed to run the commands. The first command in the README will extract the contents to the correct locations.
