### ISSUE TITLE
Available as snapshot

### ISSUE THREAD

**Issue by djeraseit** [adyanth/openwrt-tailscale-enabler#2]
Tailscale command line interface and daemon are now in the OpenWRT snapshot repository.

**Comment by adyanth** [comment]
@djeraseit Yes, it is. But afaik, that still installs it to the flash (see https://github.com/openwrt/packages/pull/15539/files), rather than running from RAM like this aims to do. There are many routers out there with 8MB flash with supports openwrt, but cannot hold the 13+13M binaries of tailscale. Let me know if that is not the case with the ipks.
